apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: kubeinvaders
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeinvaders
    helm.sh/chart: kubeinvaders-0.1.0
  name: kubeinvaders
  namespace: kubeinvaders
spec:
  rules:
  - host: kubeinvaders.local
    http:
      paths:
      - backend:
          serviceName: kubeinvaders
          servicePort: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - chart-example.local
    secretName: chart-example-tls
status:
  loadBalancer: {}